### ISSUE TITLE
[팀 보드] 오류  수정

### ISSUE THREAD

**Issue by wonju-dev** [boostcampwm-2021/WEB29-BoostTeams#143]
## 개요
팀 보드 관련 오류 수정
## 세부 개발 사항
- [x] 동시에 포스트잇을 수정하는 경우 방지
- [x] 동시에 포스트잇을 이동하는 경우 방지
- [x] 포스트잇 상대적 크기 조정
- [x] Firefox browser에서는 포스트잇 삭제가 안되는 것 같음 (확인 필요)
- [x] 마우스 포인터 좌표 문제 (비율 vs 절대 위치)
- [x] 작성자, 최근 수정자에 이름 띄우기
- [x] 팀보드page에서 Navbar 이용해서 팀 전환하면 socket 연결이 원활히 안 됨

**Comment by LeeMir** [comment]
> Firefox browser에서는 포스트잇 삭제가 안되는 것 같음 (확인 필요)

현재 포스트잇 삭제는 마우스 좌표 기준으로, `e.evt.offsetY`를 이용해 구현되어 있음
각 브라우저별로 `console.log(e.evt.offsetX, e.evt.offsetY)`를 찍어 확인해 본 결과,

#### 일반적인 포스트잇 이동
- chrome : 정상 작동
- firefox : 정상 작동
- edge : 정상 작동

#### 삭제 영역으로 이동
- chrome : 정상 작동
- firefox : 좌표가 0으로 고정(삭제 영역 위에서만)
- edge : 정상 작동

으로 확인되었습니다! 따라서 이 부분은 브라우저별로 알아봐야 할 것 같아 6주차로 미룰 생각입니다.

**Comment by LeeMir** [comment]
새로운 버그: 한 사람이 삭제 중인 포스트잇을 다른 사람이 드래그하고 있을 때 삭제가 완료되면 에러

(동시 이동 방지를 해결하면 같이 해결될 것으로 예상)
